### ISSUE TITLE
存在无法计算overdraw的情况

### ISSUE THREAD

**Issue by a2542128a** [sunbrando/ParticleEffectProfiler#5]
![image](https://user-images.githubusercontent.com/8395509/190296415-85c8a940-c7d9-4049-9b0f-84fe84a1f0d8.png)

overdraw始终为0

**Comment by sunbrando** [comment]
什么环境？
或者你可以在EffectEvla.GetOverDrawData断点试试， 这里就是计算OverDraw的

**Comment by sunbrando** [comment]
> ![image](https://user-images.githubusercontent.com/8395509/190296415-85c8a940-c7d9-4049-9b0f-84fe84a1f0d8.png)
> 
> overdraw始终为0

什么环境？
或者你可以在EffectEvla.GetOverDrawData断点试试， 这里就是计算OverDraw的

**Comment by a2542128a** [comment]
我这边一开始用的urp，后来发现这个特效数据不对，打包放到了git下载的这个工程，然后换成buildin默认的特特效shader，数据还是不对。

断点发现是GetPixActualDrawAverage() / GetPixDrawAverage() 小于1，然后被省掉了。但是感觉有些特效比这个要小，仍然会有overdraw数据

**Comment by sunbrando** [comment]
> 



> 我这边一开始用的urp，后来发现这个特效数据不对，打包放到了git下载的这个工程，然后换成buildin默认的特特效shader，数据还是不对。
> 
> 断点发现是GetPixActualDrawAverage() / GetPixDrawAverage() 小于1，然后被省掉了。但是感觉有些特效比这个要小，仍然会有overdraw数据

你把镜头离近点，因为这里意思是总绘制次数 / 摄像机里的总像素点， 摄像机离太远是有可能少于1的，所以最佳的摄像机距离应该是特效刚刚好铺满摄像机

**Comment by a2542128a** [comment]
我按您说的放大了特效，不过这个数值感觉也不太正常，播放到最大状态时当前平均overdraw只有1
![image](https://user-images.githubusercontent.com/8395509/190376895-00203aa2-671a-4396-b85b-75d0284d8412.png)

**Comment by sunbrando** [comment]
> 我按您说的放大了特效，不过这个数值感觉也不太正常，播放到最大状态时当前平均overdraw只有1 ![image](https://user-images.githubusercontent.com/8395509/190376895-00203aa2-671a-4396-b85b-75d0284d8412.png)

你Unity版本多少？

**Comment by a2542128a** [comment]
2019.4.40

**Comment by sunbrando** [comment]
> 2019.4.40

我今晚回去看看

**Comment by a2542128a** [comment]
感谢。需要我把特效打包发您么。

**Comment by sunbrando** [comment]
> 感谢。需要我把特效打包发您么。

好，加下我VX吧：Sun-27K
